### ISSUE TITLE
Adding the F-Droid collection throws hundreds of errors

### ISSUE THREAD

**Issue by nipos** [redsolver/skydroid#8]
When I add the F-Droid app collection,two different types of errors are triggered,one of them more than hundred times.
SocketException: Connection failed (OS Error: Too many open files, errno = 24), address = siasky.net, port = 443 occured 75 times during the latest try
SocketException: Failed host lookup: 'siasky.net' (OS Error: No address associated with hostname, errno = 7) occured 250 times during the latest try.
I could reproduce this on two different devices and got a report from a Mastodon user having the same problem.
I think it happens because all apps are fetched at the same time which hits the OS limit for big collections.
When I scroll down the app list,many of them are still in a loading state but I don't think that it still does anything.

**Comment by redsolver** [comment]
I just published a new version (0.2.3) which should fix this - it now limits the metadata refreshing to 100 requests per second and shows a loading dialog when adding a big collection. The new version should be available on SkyDroid in 30 to 60 minutes, on GitHub Releases in ~10 minutes.

**Comment by redsolver** [comment]
APK now available (https://github.com/redsolver/skydroid/releases/tag/v0.2.3), please check if it fixed the issue

**Comment by nipos** [comment]
I can't install the update on my tablet,it only throws a parsing error.
On my radio it gets stuck at the screen shown in my screenshot forever.
![541004](https://user-images.githubusercontent.com/6422023/106384336-93413580-63ca-11eb-8fe8-f1c84ff44bc0.jpg)
Also the loading spinner isn't spinning anymore,it totally hangs.

**Comment by redsolver** [comment]
Which device and OS version are you using?

**Comment by nipos** [comment]
- Amazon Kindle Fire 7 with Fire OS 5.6.8.0
- Archos Hello 10 with Android 8.1.0 (rooted and ungoogled)

**Comment by redsolver** [comment]
I'll take a deeper look and test it on more devices tomorrow, for now I reduced the amount of apps added by the F-Droid collection - it now only contains all apps updated after `2020-05-15`. However, ALL F-Droid are *always* available with direct links: For example this app (last updated 2012): https://to.skydroid.app/org.marcus905.wifi.ace.fdroid-app Just use the package name and attach `.fdroid-app` to it. If a `to.skydroid.app` link is opened on a device with SkyDroid installed, the app metadata is automatically loaded and displayed in SkyDroid, so the user doesn't need to care about collections or adding it manually.

**Comment by redsolver** [comment]
This should be fixed in Version 0.3.0 (https://github.com/redsolver/skydroid/releases/tag/v0.3.0), please confirm.

**Comment by nipos** [comment]
Sorry,I totally forgot about this.It's working totally fine on my radio now.Unfortunately I still can't install the update on my Kindle Fire.It aborts with a parsing error.

**Comment by bege10** [comment]
v0.5.1 on Fairphone 3, /e/OS 0.14 (based on Android 10, LineageOS, microG): Same error as in OP.

**Comment by redsolver** [comment]
> Sorry,I totally forgot about this.It's working totally fine on my radio now.Unfortunately I still can't install the update on my Kindle Fire.It aborts with a parsing error.

Unfortunately I don't have a Kindle Fire to test it myself, could you try side loading it with `adb`? This should give a better error message.

**Comment by redsolver** [comment]
> v0.5.1 on Fairphone 3, /e/OS 0.14 (based on Android 10, LineageOS, microG): Same error as in OP.

There were some DNS issues earlier this week, does the issue still persist?

**Comment by bege10** [comment]
Today it works.

**Comment by redsolver** [comment]
@nipos I'm closing this issue now because the initial bug is solved. Feel free to open a new issue for your Kindle Fire with some more `adb` debug output.

**Comment by nipos** [comment]
I think it's just too outdated and I'll likely replace it soon so I don't want to waste your time with fixing it.
